CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(120)       NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(12, 2)     NOT NULL CHECK (price > 0),
    stock       INTEGER            NOT NULL CHECK (stock >= 0),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    version     BIGINT             NOT NULL,
    sku         VARCHAR(32)        NOT NULL UNIQUE,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE INDEX idx_product_name ON product (name);
